export const mockIssues = [
  { id: 'XR-1001', title: 'Deep pothole in the left lane', description: 'Cars swerve into the next lane to avoid it, mostly near the shopping centre entrance.', category: 'Roads', severity: 'High', location: 'Durban North', lat: -29.7907, lng: 31.0275, status: 'Verified', createdAt: '2026-09-28', confirmations: 14, demo: true },
  { id: 'XR-1002', title: 'Streetlight out for a week', description: 'The whole block is dark after sunset and pedestrians are walking on the road.', category: 'Public lighting', severity: 'Medium', location: 'Umhlanga', lat: -29.727, lng: 31.084, status: 'Reported', createdAt: '2026-10-02', confirmations: 3, demo: true },
  { id: 'XR-1003', title: 'Burst water main on the verge', description: 'Clean water is running down the street and pressure has dropped for nearby homes.', category: 'Water', severity: 'High', location: 'Berea', lat: -29.85, lng: 31.001, status: 'Being fixed', createdAt: '2026-09-30', confirmations: 22, demo: true },
  { id: 'XR-1004', title: 'Illegal dumping on the corner', description: 'Builders rubble and bags of waste have been left on the pavement.', category: 'Waste', severity: 'Medium', location: 'Glenwood', lat: -29.87, lng: 30.996, status: 'Assigned', createdAt: '2026-09-25', confirmations: 9, demo: true },
  { id: 'XR-1005', title: 'Power cuts every evening', description: 'The same area loses power between 6pm and 9pm, several days in a row.', category: 'Electricity', severity: 'High', location: 'Morningside', lat: -29.83, lng: 31.02, status: 'Verified', createdAt: '2026-10-01', confirmations: 17, demo: true },
  { id: 'XR-1006', title: 'Traffic light stuck on red', description: 'The intersection is backed up at peak hours and drivers are running the light.', category: 'Safety', severity: 'High', location: 'Musgrave', lat: -29.848, lng: 31.005, status: 'Reported', createdAt: '2026-10-03', confirmations: 5, demo: true },
  { id: 'XR-1007', title: 'Blocked stormwater drain', description: 'Water pools across the road whenever it rains.', category: 'Water', severity: 'Low', location: 'Westville', lat: -29.833, lng: 30.933, status: 'Resolved', createdAt: '2026-09-12', confirmations: 11, demo: true },
  { id: 'XR-1008', title: 'Cluster of potholes near the school', description: 'Three potholes in a row on the road children use to get to school.', category: 'Roads', severity: 'Medium', location: 'Pinetown', lat: -29.819, lng: 30.859, status: 'Reported', createdAt: '2026-10-04', confirmations: 2, demo: true },
];